### ISSUE TITLE
Don't throw on ROOT::Experimental RNtuple warning

### ISSUE THREAD

**Issue by dan131riley** [cms-sw/framework-team#116]
`ROOT::Experimental::Detail::RPageSinkFile::RPageSinkFile()`, in the RNtuple package 
```
   R__WARNING_HERE("NTuple") << "The RNTuple file format will change. " <<
      "Do not store real data with this version of RNTuple!";
```
This should be added to the list of warnings that print instead of throwing.

Part of #103

**Comment by makortel** [comment]
With ROOT 6.34, I suppose we don't need to deal with this warning message anymore?

**Comment by dan131riley** [comment]
Since the storage format was frozen, this was removed in https://github.com/root-project/root/pull/16769
