### ISSUE TITLE
Allow 14_0_X files to be read in 13_0_X and 12_4_X

### ISSUE THREAD

**Issue by makortel** [cms-sw/framework-team#917]
I.e. make the tests added in https://github.com/cms-sw/cmssw/pull/44578 (backported to 14_0_X in https://github.com/cms-sw/cmssw/pull/44886) to succeed properly.

The work includes backporting https://github.com/cms-sw/cmssw/pull/42742 (https://github.com/cms-sw/framework-team/issues/662) to 13_0_X and 12_4_X, likely into special releases, and then updating the tests in 14_1_X and 14_0_X

- [x] #918
- [x] #919
- [x] #955
- [x] #956

**Comment by stahlleiton** [comment]
@makortel : Would it be possible to also backport to 13_2_X? We made a rereco of 2023 PbPb HIForward data in 14_1_X and to perform the simulation we will need to read the HLT in 13_2_X, but we are facing the problem of wrong encoding 'Z' when reading 14_1_X files in 13_2_X

**Comment by makortel** [comment]
@stahlleiton Technically likely yes, but please open an issue in `cmssw` repository to ask that. There are some questions that need further coordination that is more appropriate to be done in a `cmssw` issue rather than in a `framework-team` issue.

**Comment by stahlleiton** [comment]
> [@stahlleiton](https://github.com/stahlleiton) Technically likely yes, but please open an issue in `cmssw` repository to ask that. There are some questions that need further coordination that is more appropriate to be done in a `cmssw` issue rather than in a `framework-team` issue.

Issue in CMSSW repository: https://github.com/cms-sw/cmssw/issues/48481
